name: Deploy RICOPEKA Cloud Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > "${HOME}/gcloud-key.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcloud-key.json"
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy ricopeka_ai \
            --runtime python311 \
            --trigger-http \
            --allow-unauthenticated \
            --entry-point ricopeka_ai \
            --source ./functions \
            --region us-central1 
